### ISSUE TITLE
free course for android development 

### ISSUE THREAD

**Issue by ojasjain24** [avinash201199/Free-courses-with-Certificates#10]
The Associate Android Developer Certification provides end-to-end training, culminating in an industry-recognized certification. The certification exam can be done online from wherever you're located and is performance-based—mirroring real-world developer tasks, like adding functionality to an app and fixing bugs in existing code.

After completing the Associate Android Developer Certification exam, you'll receive a digital badge you can use to promote yourself to potential employers. You can include your digital badge in your email signature and share it on sites like LinkedIn and Twitter.

You’ll also be featured on the official Google Developers Certification Directory, which is searchable by employers, and have access to free resources, including interview tips, mock interviews, resume-building workshops, career coaching sessions, and more.

Course Link :  https://grow.google/androiddev/#?modal_active=none

**Comment by avinash201199** [comment]
@ojasjain24  certification exam is free or paid ?

**Comment by ojasjain24** [comment]
The Android Basics in Kotlin training is free.

The Associate Android Developer Certification exam costs $149 USD for one exam attempt. Please note that local pricing may vary based on your country of origin.

**Comment by avinash201199** [comment]
@ojasjain24  please add free cousse with certification only :)
