### ISSUE TITLE
I want to add a free certification course for GitHub beginners.

### ISSUE THREAD

**Issue by Ramank2002** [avinash201199/Free-courses-with-Certificates#121]
Hello sir,
I am Raman Kumar Gupta , with GitHub Id - Ramank2002
I want to contribute to your repository by adding a free certification course on GitHub from a renowned learning platform GreatLearning.com.
Kindly consider my contribution and I'll be very thankful to you.

Regards

**Comment by SuryanshSinha2612** [comment]
Hello sir,
I am Suryansh Sinha , with GitHub Id -SuryanshSinha2612 and LinkedIn ID -https://www.linkedin.com/in/suryansh-sinha-40273a240/
I want to contribute to your repository by adding a free certification course from a World's #1 online bootcamp Simplilearn.
link to the website " https://lms.simplilearn.com/dashboard"
Kindly consider my contribution and I'll be very thankful to you😊.

Regards
