### ISSUE TITLE
Data structure in c by great learning

### ISSUE THREAD

**Issue by ojasjain24** [avinash201199/Free-courses-with-Certificates#13]
This course contains 2 hours of video lecture focusing on Implementation of Data Structures using C programming language.

https://www.greatlearning.in/academy/learn-for-free/courses/data-structures-in-c

**Comment by avinash201199** [comment]
will assign this one later :) 
2 pr is already accepted

**Comment by ojasjain24** [comment]
@avinash201199 PR for this is already accepted. #14

**Comment by avinash201199** [comment]
okay then closing the issue
