### ISSUE TITLE
Harvard CS50 Introduction to Computer Science provided by edX

### ISSUE THREAD

**Issue by anushkadubey** [avinash201199/Free-courses-with-Certificates#18]
A beginner level free online computer science course, explaining in detail about algorithms and problem solving. It is a really great course for people just starting out with coding, although the certificate is available only after upgrade, but otherwise the whole course is available for free. Let me know if I can add this here!

**Comment by avinash201199** [comment]
but the course should also provide free certificate , is that so ?

**Comment by anushkadubey** [comment]
the course is free but the certificate is given after upgrade, which has some fee.

**Comment by avinash201199** [comment]
> the course is free but the certificate is given after upgrade, which has some fee.

so this repository is not for that , please add some another course which is completely  free with ceritficate.

**Comment by anushkadubey** [comment]
okay, no problem then. I will search for and add some other courses.

**Comment by avinash201199** [comment]
> okay, no problem then. I will search for and add some other courses.

Great :)
Thank you Anushka !
