### ISSUE TITLE
Want to add MySQL Basics course

### ISSUE THREAD

**Issue by kr84abhijeet** [avinash201199/Free-courses-with-Certificates#197]
Hello Sir,
I am Kumar Abhijeet with GitHub id - kr84abhijeet
I want to contribute to your repository by adding a course "My SQL Basics".
Kindly consider my contribution. I'll be very thankful to you for this opportunity.

Regards,
Kumar Abhijeet

**Comment by avinash201199** [comment]
kindly check contributing.md file to contribute
