### ISSUE TITLE
Get Ahead with Front-end Development

### ISSUE THREAD

**Issue by RakshaFauzdar** [avinash201199/Free-courses-with-Certificates#20]
An interview-centric course that focuses on front-end development and problem-solving!

This 5 weeks course is designed keeping in mind all the important topics that are frequently asked in top product-based companies. This course is totally free and  one needs to score atleast 50 marks  to earn a certificate.

link : https://practice.geeksforgeeks.org/courses/frontend-dev?vC=1

**Comment by avinash201199** [comment]
please provide website url ?
