### ISSUE TITLE
Adding HTML and CSS to index.html

### ISSUE THREAD

**Issue by nik-agarwal12** [avinash201199/Free-courses-with-Certificates#226]
Hey Coder @avinash201199 , assign me this issue . I want to make a the index page complete.

**Comment by avinash201199** [comment]
can you explaine more

**Comment by nik-agarwal12** [comment]
Presently we don't have any content in the home page. I will fill the
contents into the home page and will make the page look beautiful

**Comment by tejus0** [comment]
Hey @avinash201199 I want to improve your website by adding a course slider below the navigation bar which will show the featured courses . Currently the featured courses are static and looks simple and naive . 
So assign me this issue under hacktoberfest if you like my idea .
