### ISSUE TITLE
want to add Beginner Course on Programming and Coding Fundamentals by Haris Samingan

### ISSUE THREAD

**Issue by BinilTomJose1278** [avinash201199/Free-courses-with-Certificates#341]

**Comment by avinash201199** [comment]
we are adding only free course with certificates

**Comment by BinilTomJose1278** [comment]
I have changed the course name, this course is absolutely free and so much reliable to study for a beginner

**Comment by BinilTomJose1278** [comment]
Can u accept my pull request after going through it?
