### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by Tejas124** [avinash201199/Free-courses-with-Certificates#354]
There is repetition of 'Digital Marketing' section in Readme.md file. I would like to fix this. 
Can you please assign me this task?

**Comment by Tejas124** [comment]
This issue has been solved. I have created another PR where I have removed some repetitive course links. 
Please check it.

**Comment by Tejas124** [comment]
Thank you for accepting the issue. Will this be added as an contribution for Hacktoberfest 23 ?

**Comment by avinash201199** [comment]
> Thank you for accepting the issue. Will this be added as an contribution for Hacktoberfest 23 ?

yes , the repo which has tags hacktoberfest and hacktoberfest-accepted are considered for the hacktoberfest participation

**Comment by Tejas124** [comment]
Okay, but my Hacktoberfest dashboard still shows 0/4 PRs. Why is it so? This PR should be accepted right ?

**Comment by avinash201199** [comment]
> Okay, but my Hacktoberfest dashboard still shows 0/4 PRs. Why is it so? This PR should be accepted right ?

issues are not counted as successful contribution , you need to create pull request with changes you have done . After accepting pr request in few hours it will refelect in hacktoberfest site
!

**Comment by avinash201199** [comment]
> > Okay, but my Hacktoberfest dashboard still shows 0/4 PRs. Why is it so? This PR should be accepted right ?
> 
> issues are not counted as successful contribution , you need to create pull request with changes you have done . After accepting pr request in few hours it will refelect in hacktoberfest site !

I closed this issue because it was created previous year !
