### ISSUE TITLE
Want to add the Data Structures and Algorithms course (in Python) offered by Google.

### ISSUE THREAD

**Issue by sagacious-satadru** [avinash201199/Free-courses-with-Certificates#376]
The course is available for free on Udacity.

**Comment by sagacious-satadru** [comment]
Thank you. I've added the course link and description. This was for Hacktoberfest 2022, although I'm not sure if this can still count.

**Comment by avinash201199** [comment]
It will not count but I will accept it , Thank you for your contribution !
