### ISSUE TITLE
Free Android Development Course + Certificate

### ISSUE THREAD

**Issue by JyotimoyKashyap** [avinash201199/Free-courses-with-Certificates#4]
Hi, I am participating in Hacktoberfest 2021, and I have found a free android development course that can be very helpful for many with a free certificate. 

Link for the course : [Here](https://www.educba.com/software-development/courses/free-android-app-development-course/)

Please assign me this issue.

**Comment by avinash201199** [comment]
@JyotimoyKashyap go ahead

**Comment by JyotimoyKashyap** [comment]
This issue is resolved, and I think we can close this issue.
