### ISSUE TITLE
separating css to individual components 

### ISSUE THREAD

**Issue by Pavan-Rajesh** [avinash201199/Free-courses-with-Certificates#416]
If we separate css for the individual components it would be easy to modify and maintain the code

**Comment by anish-patro** [comment]
If @Pavan-Rajesh is not working on it, can you please assign it to me.

**Comment by Pavan-Rajesh** [comment]
@anish-patro  yes you can do it

**Comment by anish-patro** [comment]
> @anish-patro yes you can do it reply to this if you have started to work

yes

**Comment by anish-patro** [comment]
#419

**Comment by anish-patro** [comment]
#419

**Comment by anish-patro** [comment]
i have a doubt, isn't this issue comes under hacktoberfest?
