### ISSUE TITLE
Bug: "Featured Section" Content is Crossing its Set Width

### ISSUE THREAD

**Issue by iamRabia-N** [avinash201199/Free-courses-with-Certificates#417]
The content of the "Featured Section" is crossing its set width, which is forcing the user to scroll in order to view the content on the right side. We can correct it by resetting the width according to different screen sizes.

**Screenshots**
![img (1)](https://github.com/avinash201199/Free-courses-with-Certificates/assets/115794049/4cbcd90d-392e-445e-a1fb-ec6429d2e2a9)

![img (2)](https://github.com/avinash201199/Free-courses-with-Certificates/assets/115794049/94b9c4f8-b44c-47d6-b212-a0524d2c00a4)

**Comment by Pavan-Rajesh** [comment]
make a separate component(parent)
 for the right one and set the children of the component to 100%width
