### ISSUE TITLE
Create a website for this repo - comment down, I will assign the issue to you !

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/Free-courses-with-Certificates#42]

**Comment by RESHMA-RAMESH** [comment]
I can create a website for this repo. but I want the issues to be broken down into smaller pieces, like template creation, UI enhancement, Content updation... rather than having one issue that says 'create a website'

**Comment by avinash201199** [comment]
> I can create a website for this repo. but I want the issues to be broken down into smaller pieces, like template creation, UI enhancement, Content updation... rather than having one issue that says 'create a website'

you are right , it should be broken down into smaller portion , you can start working on  which you can contribute rest will see later .

**Comment by Sonukumarkeshri4** [comment]
Can I contribute as well, please assign some issues of this task for me.

**Comment by avinash201199** [comment]
> Can I contribute as well, please assign some issues of this task for me.

wait for @RESHMA-RAMESH to add some structure of the website , after that you can contribute in that.

**Comment by RESHMA-RAMESH** [comment]
Here s an other PR https://github.com/avinash201199/Free-courses-with-Certificates/pull/57

**Comment by RESHMA-RAMESH** [comment]
> Can I contribute as well, please assign some issues of this task for me.

@avinash201199 @Sonukumarkeshri4 , with this [PR](https://github.com/avinash201199/Free-courses-with-Certificates/pull/57),  the content is loading from the json. @Sonukumarkeshri4 , I have added just one data set to test its behaviour, you can load the other data as well if you like

**Comment by avinash201199** [comment]
> > Can I contribute as well, please assign some issues of this task for me.
> 
> @avinash201199 @Sonukumarkeshri4 , with this [PR](https://github.com/avinash201199/Free-courses-with-Certificates/pull/57), the content is loading from the json. @Sonukumarkeshri4 , I have added just one data set to test its behaviour, you can load the other data as well if you like

https://avinash201199.github.io/Free-courses-with-Certificates/   website is now running , now please add all the courses

**Comment by RESHMA-RAMESH** [comment]
@avinash201199  https://github.com/avinash201199/Free-courses-with-Certificates/pull/58
