### ISSUE TITLE
Improving about page

### ISSUE THREAD

**Issue by D-Aman-S** [avinash201199/Free-courses-with-Certificates#425]
The current About page is very minimal with just a simple text in the center
![image](https://github.com/avinash201199/Free-courses-with-Certificates/assets/75574963/68f82ec6-7a8e-403c-afa1-cfb81e605701)

I want to make some UI enhance to it, I also want to display a list of all contributors below the owner's name

**Comment by Vikas3100** [comment]
Hi @D-Aman-S ,
I would like to contribute & I will take a look into this as my first step.

**Comment by Vikas3100** [comment]
Hi @avinash201199 ,
I would like to contribute & I will take a look into this as my first step.

**Comment by avg77** [comment]
@avinash201199 Can i take up this issue? It seems unattended at the moment. 
I plan to make it look somewhat like this: 
![hg](https://github.com/avinash201199/Free-courses-with-Certificates/assets/91598955/785ee1dd-4398-40dc-867f-e8c7227880d1)
