### ISSUE TITLE
Verify and remove coursera links as most of them are paid courses

### ISSUE THREAD

**Issue by RESHMA-RAMESH** [avinash201199/Free-courses-with-Certificates#49]

**Comment by avinash201199** [comment]
hey can you please add the index and style file in main page only so that it can be hosted using github pages , delete the website folder

**Comment by avinash201199** [comment]
> hey can you please add the index and style file in main page only so that it can be hosted using github pages , delete the website folder

can you please do this ?

**Comment by RESHMA-RAMESH** [comment]
> > hey can you please add the index and style file in main page only so that it can be hosted using github pages , delete the website folder
> 
> can you please do this before further contribution

Sure, i ll update the structure, i didn't notice your comment since this is a separate issue

**Comment by RESHMA-RAMESH** [comment]
So @avinash201199, do you want all html, css and js code in same file or just in root folder should be ok?

**Comment by avinash201199** [comment]
> So @avinash201199, do you want all html, css and js code in same file or just in root folder should be ok?

I have edited it , now you can go for furthor commit
