### ISSUE TITLE
🐞 Adding Logo to the website.

### ISSUE THREAD

**Issue by PranjalGupta22** [avinash201199/Free-courses-with-Certificates#571]
**Issue Description:**

I think the website is well-constructed, user-friendly, and informative, but it's missing a vital element - a logo. A logo is a crucial component of any website; it is a visual identifier that communicates its essence and values. I believe that by adding a logo, we can take our project to the next level.

Also have to fix this horizontal scroller at the bottom.

This issue aims to address the absence of a logo and to initiate the process of incorporating one into our project's web presence.

**Screenshot**
![image](https://github.com/avinash201199/Free-courses-with-Certificates/assets/123003273/f2cf3836-efda-42d5-b2e2-28fd0ba5f9fd)

✅ I would like to work on this issue. "Also would love to have some additional suggestions and ideas."

**Comment by avinash201199** [comment]
all the best

**Comment by PranjalGupta22** [comment]
Sure I'll keep that in mind.
Thank you!

**Comment by PranjalGupta22** [comment]
**Subject:** Logo Design: Your Input Needed!

Hey, I'm sorry for the delay. But, I wanted to reach out to gather some information regarding the logo design. I'm excited to work on it and create a logo that truly represents your brand. To make this process smooth and ensure the final result is a perfect fit for you, it would be really helpful if you could share a bit of your creative input.

Here's what I'm hoping to gather:

**Brand Name:** Please let me know the exact brand name you'd like to see in the logo. If you have any specific variations or taglines to include, please let me know.

**Additional Details:** If there are any particular elements, symbols, or imagery you'd like to incorporate into the logo, please share your thoughts, or I could go with the option that resonates with me.

Looking forward to your response, and thanks in advance for your time and input.
