### ISSUE TITLE
Add New course

### ISSUE THREAD

**Issue by Mayureshd-18** [avinash201199/Free-courses-with-Certificates#579]
I want to add Harvards CS50 - Introduction to databases with SQL.

Website : https://cs50.harvard.edu/sql/2023/

**Comment by avinash201199** [comment]
will they provide free certificate after completion ?

**Comment by Mayureshd-18** [comment]
Yes. All CS50 certificates have the same format. After completion of all the exercises and a project(if there) then we get the certificate.
