### ISSUE TITLE
python GUI tkinter course

### ISSUE THREAD

**Issue by MohitHire** [avinash201199/Free-courses-with-Certificates#589]
hi, I want to add free python tkinter GUI course please assign me this issue, I really want to work on this
thank you

**Comment by avinash201199** [comment]
will they provde certificate after completion ?

**Comment by MohitHire** [comment]
yes they wil provide certificae of completion
![python tkinter](https://github.com/avinash201199/Free-courses-with-Certificates/assets/135497031/2d5fb841-c16f-465a-a7e9-73abbc3ae22d)
