### ISSUE TITLE
Errors in allcourses.json

### ISSUE THREAD

**Issue by biswabaibhab007** [avinash201199/Free-courses-with-Certificates#594]
there are numerous errors in the *allcourses.json* file. Although I did tried fixing them but after fixing all the errors the localhost does not start. I would really apprecitate if someone can fix this.

**Comment by Narennnnn** [comment]
Hey @biswabaibhab007 I fixed the issue #594 
![Screenshot from 2023-10-15 13-34-25](https://github.com/avinash201199/Free-courses-with-Certificates/assets/120191897/de71fc53-1116-4819-b01d-d0c174d2d4b6)

Assign me the issue so that I can create PR. Thanks!

**Comment by Narennnnn** [comment]
I have created a PR. After merge you can start working @biswabaibhab007
