### ISSUE TITLE
Free react course in 1 hour + CERTIFICATE

### ISSUE THREAD

**Issue by Ankurrsingh** [avinash201199/Free-courses-with-Certificates#6]
I am participating in Hacktoberfest 2021, and I have found a free react course.

LINK : [https://www.udemy.com/course/react-basic-in-just-1-hour/](url)

**Comment by avinash201199** [comment]
@Ankurrsingh you have to add free courses with certificate,in this course they will not provide certificate so add another , I'm closing the issue.
