### ISSUE TITLE
Add javascript course

### ISSUE THREAD

**Issue by hpk129** [avinash201199/Free-courses-with-Certificates#622]
i want to add a free js course, pls assign this task to me

**Comment by hpk129** [comment]
sir, ive added the course pls see to it  :)

**Comment by DevanshKyada27** [comment]
Hey @avinash201199 can you please assign me this issue.
Want to work on it.

**Comment by DevanshKyada27** [comment]
Hey @avinash201199 if you liked the PR could you please merge it.
