### ISSUE TITLE
Update all the courses from readme to the website list

### ISSUE THREAD

**Issue by RESHMA-RAMESH** [avinash201199/Free-courses-with-Certificates#67]

**Comment by RESHMA-RAMESH** [comment]
@avinash201199 Here is the PR. #59 - Added Angular & block chain courses to main.js #66

I'll update the list by batch as and when I get time.

**Comment by avinash201199** [comment]
try to update all by ones because you have already many pr's in this repo , they review the pr so try to not make so many pr in the same repository :)
