### ISSUE TITLE
Add AWS course

### ISSUE THREAD

**Issue by Ayaan49** [avinash201199/Free-courses-with-Certificates#675]
# Description
I want to add free AWS course.

# Title
Amazon Web Services (AWS) - Zero to Hero

# Objectives
- Launch an AWS EC2 WordPress web server
- Create and connect to an AWS relational database server
- Create a NodeJS highly available and fault tolerant web application environment
- Upload files to AWS S3
- Send email with AWS SES
- Monitor and alert with AWS CloudWatch
- How to use AWS for free.

**Comment by Smritigit1202** [comment]
Please assign me this task

**Comment by Ayaan49** [comment]
Please read carefully before commenting on an issue. The issue has already been assigned to me, and I have created a PR as well. So there is no point in asking to be assigned for this issue. Better create your own issue. @Smritigit1202
