### ISSUE TITLE
Add new course for Prompt Engineeering

### ISSUE THREAD

**Issue by JatinPhogat** [avinash201199/Free-courses-with-Certificates#723]
Hey @avinash201199 there is only one course for Prompt Engineering . I would like to add one more for "Prompt Engineering for CharGPT" in that . Please assign it to me .

**Comment by JatinPhogat** [comment]
Also it is not mentioned in allcourses.json

**Comment by JatinPhogat** [comment]
Hi , i have linked a pull request for it please check it , also please add a label other than hacktoberfest as i am particpating in hack squad so hacktoberfest wont be counted . Please add something like label:feature
Thankuuu

**Comment by avinash201199** [comment]
> Hi , i have linked a pull request for it please check it , also please add a label other than hacktoberfest as i am particpating in hack squad so hacktoberfest wont be counted . Could you Please add something like label:feature Thankuuu

please add free courses with free certificates
